#!/bin/bash
#
#Wifi config - if no prefered Wifi generate a hotspot

#enter required ssids: ssids=('ssid1' 'ssid2')
CurrentSsid = $(bash /home/pi/installer/SensorPlatform/includedFiles/GetCurrentSSID.sh)
#ssids=('NEVERHITSTHISPROABBLY' '$CurrentSsid')
echo $CurrentSsid


#Main script
#createAdHocNetwork()
#{
#    ip link set dev wlan0 down
#    ip a add 10.0.0.5/24 dev wlan0
#    ip link set dev wlan0 up
#    service dnsmasq start
#    service hostapd start
#}

#connected=false

#for ssid in "${ssids[@]}"
#do
#    if iw dev wlan0 scan ap-force | grep $ssid > /dev/null
#    then
#        wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf > /dev/null 2>&1
#        if dhclient -1 wlan0
#        then
#            connected=true
#            break
#        else
#            wpa_cli terminate
#            break
#        fi
#    fi

#done

#if ! $connected; then
#    createAdHocNetwork
#fi

