#!/bin/bash
#
#Wifi config - if no dhclient Wifi generate a hotspot
#Main script

createAdHocNetwork()
{
    ip link set dev wlan0 down
    ip a add 10.0.0.5/24 dev wlan0
    ip link set dev wlan0 up
    service dnsmasq start
    service hostapd start
}

connected=false
if dhclient -1 wlan0
then
    connected=true
    break
else
    wpa_cli terminate
    break
fi

if ! $connected; then
    createAdHocNetwork
fi
